/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'libcurl.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./libcurl.android-arm64.node')
          } else {
            nativeBinding = require('@tocha688/libcurl-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'libcurl.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./libcurl.android-arm-eabi.node')
          } else {
            nativeBinding = require('@tocha688/libcurl-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'libcurl.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./libcurl.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@tocha688/libcurl-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'libcurl.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./libcurl.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@tocha688/libcurl-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'libcurl.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./libcurl.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@tocha688/libcurl-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'libcurl.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./libcurl.darwin-universal.node')
      } else {
        nativeBinding = require('@tocha688/libcurl-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'libcurl.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./libcurl.darwin-x64.node')
          } else {
            nativeBinding = require('@tocha688/libcurl-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'libcurl.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./libcurl.darwin-arm64.node')
          } else {
            nativeBinding = require('@tocha688/libcurl-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'libcurl.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./libcurl.freebsd-x64.node')
      } else {
        nativeBinding = require('@tocha688/libcurl-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'libcurl.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./libcurl.linux-x64-musl.node')
            } else {
              nativeBinding = require('@tocha688/libcurl-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'libcurl.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./libcurl.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@tocha688/libcurl-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'libcurl.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./libcurl.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@tocha688/libcurl-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'libcurl.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./libcurl.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@tocha688/libcurl-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'libcurl.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./libcurl.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@tocha688/libcurl-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'libcurl.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./libcurl.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@tocha688/libcurl-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'libcurl.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./libcurl.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@tocha688/libcurl-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'libcurl.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./libcurl.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@tocha688/libcurl-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'libcurl.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./libcurl.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@tocha688/libcurl-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { setLibPath, getLibPath, CurlOpt, CurlInfo, CurlMOpt, CurlError, CurlHttpVersion, CurlWsFlag, CurlSslVersion, CurlIpResolve, CurlImpersonate, Curl, globalInit, globalCleanup, getVersion, getDefaultDirName, getDefaultLibPath, CurlMulti, socketIsReadable, socketIsWritable } = nativeBinding

module.exports.setLibPath = setLibPath
module.exports.getLibPath = getLibPath
module.exports.CurlOpt = CurlOpt
module.exports.CurlInfo = CurlInfo
module.exports.CurlMOpt = CurlMOpt
module.exports.CurlError = CurlError
module.exports.CurlHttpVersion = CurlHttpVersion
module.exports.CurlWsFlag = CurlWsFlag
module.exports.CurlSslVersion = CurlSslVersion
module.exports.CurlIpResolve = CurlIpResolve
module.exports.CurlImpersonate = CurlImpersonate
module.exports.Curl = Curl
module.exports.globalInit = globalInit
module.exports.globalCleanup = globalCleanup
module.exports.getVersion = getVersion
module.exports.getDefaultDirName = getDefaultDirName
module.exports.getDefaultLibPath = getDefaultLibPath
module.exports.CurlMulti = CurlMulti
module.exports.socketIsReadable = socketIsReadable
module.exports.socketIsWritable = socketIsWritable
